首先导入 `torch` 。虽然它被称为PyTorch，但是应该导入 `torch` 而不是 `pytorch` 。

In [15]:
import torch

张量 (Torch) 表示一个数值组成的数组，这个数组可能有很多维度。`torch.arange` 表示生成一个0～11的数组，和 `numpy.arange` 相同。

In [16]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


- 可以用 `shape` 属性访问张量的形状、维度
- 可以用 `numel` 方法访问张量的元素总数

使用 `torch.tensor` 传入一个列表/元组/ndarray等等，创建一个张量，和 `numpy.array` 一样。

In [17]:
y = torch.tensor([1,2,3,4,5,6,7,8,9,10, 11, 12])
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [18]:
print(x.shape)
print(x.numel())

torch.Size([12])
12


使用 `reshape` 方法改变一个张量的形状，用法和 `numpy.reshape` 相同。

In [19]:
x = x.reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


可以使用 `torch.zeros` 或者 `torch.ones` 创建全是0或者1的张量，使用方法和 `numpy` 中的一样。

In [20]:
# 分别创建一维，二维，三维的张量
a = torch.zeros(3)
print(a)
a = torch.zeros(3, 4)
print(a)
a = torch.zeros(3, 4, 5)
print(a)

tensor([0., 0., 0.])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


+, -, *, / 运算和 `numpy` 中的用法都相同，按照对应位置上的元素进行运算，不再赘述。

可以用 `T` 属性得到一个张量的转置矩阵，依然和 `numpy` 类似。

In [21]:
a = torch.arange(0, 12).reshape(3, 4)
print(a)
print(a.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


使用 `clone` 方法对张量进行复制，区别于 在 `numpy` 中使用 `copy` 方法进行复制。

In [22]:
b = a.clone()
b = b ** 2
print(a)
print(b)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])


使用 `sum` 方法进行求和，可以指定按照行列进行求和。使用 `dim` 参数可以对指定的行列进行压缩，`dim=0` 将一个二维张量按照行进行压缩，`dim=1` 将一个二维张量按照列进行压缩。

In [24]:
print(x.shape)
print(x)
print(x.sum())
print(x.sum(dim=0))
print(x.sum(dim=1))

torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(66)
tensor([12, 15, 18, 21])
tensor([ 6, 22, 38])
