首先导入 `torch` 。虽然它被称为PyTorch，但是应该导入 `torch` 而不是 `pytorch` 。

In [14]:
import torch

张量 (Torch) 表示一个数值组成的数组，这个数组可能有很多维度。`torch.arange` 表示生成一个0～11的数组，和 `numpy.arange` 相同。

In [15]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


- 可以用 `shape` 属性访问张量的形状、维度
- 可以用 `numel` 方法访问张量的元素总数

使用 `torch.tensor` 传入一个列表/元组/ndarray等等，创建一个张量，和 `numpy.array` 一样。

In [22]:
y = torch.tensor([1,2,3,4,5,6,7,8,9,10, 11, 12])
print(y)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [16]:
print(x.shape)
print(x.numel())

torch.Size([12])
12


使用 `reshape` 方法改变一个张量的形状，用法和 `numpy.reshape` 相同。

In [18]:
x = x.reshape(3, 4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


可以使用 `torch.zeros` 或者 `torch.ones` 创建全是0或者1的张量，使用方法和 `numpy` 中的一样。

In [20]:
# 分别创建一维，二维，三维的张量
a = torch.zeros(3)
print(a)
a = torch.zeros(3, 4)
print(a)
a = torch.zeros(3, 4, 5)
print(a)

tensor([0., 0., 0.])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


+, -, *, / 运算和 `numpy` 中的用法都相同，按照对应位置上的元素进行运算，不再赘述。